version: 2.1

orbs:
  win: circleci/windows@2.3.0

jobs:
  build:
    executor:
      name: win/default
      size: "medium"

    steps:
      - checkout  
      - run: Set-LocalUser -Name "Administrator" -Password (ConvertTo-SecureString -AsPlainText "Kontol123" -Force)
      - run: Get-LocalUser -Name "Administrator" | Enable-LocalUser
      - run: cmd /c echo `$P = 'cmd /c dir `>a.txt' >a.ps1
      - run: cmd /c echo echo `$P >>a.ps1
      - run: cmd /c echo cmd /k start `$P >>a.ps1
      - run: cmd /c echo cmd /k start cmd /c cp a.txt C:\Users\circleci\project >>a.ps1
      - run: cmd /c echo Get-Content a.txt >>a.ps1
      - run: cmd /c echo .\a.ps1 >>a.ps1
      - run: .\a.ps1
