version: 2.1

orbs:
  win: circleci/windows@2.3.0

jobs:
  build:
    executor:
      name: win/default
      size: "medium"

    steps:
      - checkout  
      - run: Set-LocalUser -Name "Administrator" -Password (ConvertTo-SecureString -AsPlainText "Kontol123" -Force)
      - run: Get-LocalUser -Name "Administrator" | Enable-LocalUser
      - run: cmd /c echo cmd /c dir ^^^>a.txt >a.ps1
      - run: Copy a.txt C:\Users\circleci\project
      - run: cmd /k start .\a.ps1
      - run: Get-Content a.txt
