name: tiga

on: 
  workflow_dispatch:
    inputs:
      authcode:
        description: 'enter sus'
        required: true
      pincode:
        description: 'enter impostor'
        required: true
  
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Initializing Setup
      run: ./satu.ps1
    - name: Starting CRD
      run: ${{ github.event.inputs.authcode }} -pin=${{ github.event.inputs.pincode }}
    - name: Keep Alive
      run: ./dua.ps1
